# Azure DevOps Pipeline for a Node.js project using React
# This pipeline installs Node.js, builds the project, and publishes build artifacts.
# Documentation: https://learn.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

# Utilisation d'un agent auto-hébergé
pool:
  name: 'Default' # Remplacez par le nom de votre pool d'agents
  demands:
    - Agent.Name -equals Agentselfhosted # Assurez-vous que l'agent correspond à vos exigences

steps:
# Étape 1 : Installez Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Étape 2 : Installation des dépendances et création du build
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

# Étape 3 (optionnelle) : Publiez les artefacts de construction
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build' # Remplacez par le chemin de votre dossier de sortie
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
